services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin123'
      MYSQL_DATABASE: 'flask-crud'
      MYSQL_ROOT_PASSWORD: 'admin123'
    ports:
      - "3307:3306"
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      # - /d/github/sample-flask-auth/mysql # pc-home
      - /home/andreza.santos@aditec.local/Documents/macsDev/sample-flask-auth/mysql # pc-work